version: '2'
services:
  back:
    build: .
    command: yarn start
    volumes:
      - .:/app/back
      - /app/back/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  front:
    build: .
    command: yarn start
    volumes:
      - .:/app/front
      - /app/front/node_modules
    ports:
      - "3000:3000"