services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    expose:
      - "8080"
    command: "yarn start"
  db:
    image: mongo
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db
    